#!/usr/bin/env python3
"""Generates src/render/sprites/menu_art.lua: menu hub art drawn as pixel grids.

* one floating island per world (forest, desert, crystal, inferno, sky, void) with the
  stone dais the page's star element stands on (tools/menu_art/island_art.py)
* the golden and obsidian chests (tools/menu_art/chest_art.py)

Run it after changing the generators, then re-bake the atlas (`love tools/bake`).
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "menu_art"))
import island_art  # noqa: E402
import chest_art  # noqa: E402

OUT = os.path.join(os.path.dirname(HERE), "src", "render", "sprites", "menu_art.lua")
WORLD_ORDER = ["forest", "desert", "crystal", "inferno", "sky", "void"]


def lua_grid(rows):
    return "{\n" + "".join('        "%s",\n' % r for r in rows) + "    }"


def lua_palette(pal):
    return "{ " + ", ".join('%s = "%s"' % (k, v) for k, v in sorted(pal.items())) + " }"


def main():
    out = ["-- src/render/sprites/menu_art.lua",
           "-- GENERATED by tools/make_menu_sprites.py: do not edit by hand.",
           "-- Menu hub art: one floating island per world (dais in the middle) and the chests.",
           "",
           "local MenuArt = {}",
           "",
           "-- World index (WorldManager.CHAPTERS order) -> island sprite name",
           "MenuArt.ISLANDS = { %s }" % ", ".join('"menu_island_%s"' % w for w in WORLD_ORDER),
           "-- Dais centre, in pixels from the island sprite's top-left corner (before scaling)",
           "MenuArt.DAIS_X, MenuArt.DAIS_Y = %d, %d" % (island_art.CX + 1, 5 + 1),
           ""]
    for w in WORLD_ORDER:
        rows = island_art.grid(island_art.WORLDS[w])
        out.append("local ISLAND_%s = %s" % (w.upper(), lua_grid(rows)))
        out.append("")
    out.append("local CHEST_GOLD = %s" % lua_grid(chest_art.grid(False)))
    out.append("")
    out.append("local CHEST_OBSIDIAN = %s" % lua_grid(chest_art.grid(True)))
    out.append("")
    out.append("function MenuArt.define(atlas)")
    out.append('    local function d(name, grid, pal)')
    out.append('        atlas:define(name, { frames = { grid }, palette = pal, outline = "181425", anchor = "topleft" })')
    out.append("    end")
    for w in WORLD_ORDER:
        out.append('    d("menu_island_%s", ISLAND_%s, %s)' % (w, w.upper(), lua_palette(island_art.WORLDS[w]["pal"])))
    out.append('    d("menu_chest_gold", CHEST_GOLD, %s)' % lua_palette(chest_art.PAL_GOLD))
    out.append('    d("menu_chest_obsidian", CHEST_OBSIDIAN, %s)' % lua_palette(chest_art.PAL_OBSIDIAN))
    out.append("end")
    out.append("")
    out.append("return MenuArt")
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
